---
resources:
  - name: resource-kirby
    type: git
    source:
      uri: https://github.com/Kuriyano/concourse-tutorial-clone.git
      branch: master

jobs:
  - name: job-hello-world
    public: true
    plan:
      - get: resource-kirby
      - task: hello-world
        file: resource-kirby/tutorials/basic/task-hello-world/task_hello_world.yml
